### ISSUE TITLE
sampleQC not working

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#233]
Hi,
I'm getting this error in snakemake sampleQC:
```
Structuring dependencies...
Dependencies file generated at: /tmp/tmp0qhwfbfs

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    QC/UDP.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

**Comment by nickhsmith** [comment]
Could you please let us know which version of drop you are using? and how you ran the pipeline, did you call all modules or just MAE? 
`drop --version`

Additionally could you please send us your config file, and the entirety of the logging information. It's hard to diagnose what the problem may be from just this snippet. Thanks

**Comment by gevro** [comment]
drop --version
```
drop, version 1.0.5
```

How I ran sampleQC (I ran this after running aberrantExpression and aberrantSplicing. I have not yet run mae):
```
snakemake sampleQC --cores 2
```

Error/output
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplncxvu0h

Unlocking working directory.
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmp0qhwfbfs

Building DAG of jobs...
WorkflowError:
WorkflowError:
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
    QC/UDP.md
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_QC_Datasets.md
```

config.yaml
```
ProjectTitle: Test
root: /gpfs/scratch/drop/root            # root directory of all intermediate output
htmlOutputPath: /gpfs/scratch/drop/htmlOutput  # path for HTML rendered reports
indexWithFolderName: true # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver

sampleAnnotation: /gpfs/scratch/drop/samples.tsv

geneAnnotation:
# multiple annotations with custom names are possible
# <annotation_name> : <path to gencode v29 annotation>
  v32: /gpfs/data/reference-files/GRCh38_gencode-STAR/gencode.v32.primary_assembly.annotation.gtf

genomeAssembly: hg38  # either hg19 or hg38
genome: /gpfs/data/reference-files/GRCh38_gencode-STAR/GRCh38_primary_assembly_genome.fa

exportCounts:
  # specify which gene annotations to include and which 
  # groups to exclude when exporting counts
  geneAnnotations:
  - v32
  excludeGroups:
  - null

aberrantExpression:
  groups: 
  - GTEX100
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 0.05
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3

aberrantSplicing:
  groups:
  - GTEX100
  recount: false
  longRead: false
  keepNonStandardChrs: false
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.3
  maxTestedDimensionProportion: 6

mae:
  groups:
  - UDP
  genome: /gpfs/data/reference-files/GRCh38_gencode-STAR/GRCh38_primary_assembly_genome.fa
  gatkIgnoreHeaderCheck: true
  padjCutoff: .05
  allelicRatioCutoff: 0.8
  addAF: true
  maxAF: .001
  maxVarFreqCohort: .05
  # VCF-BAM matching
  qcVcf: /gpfs/data/reference-files/hg38-gatk/qc_vcf_1000G.hg38.vcf.gz       # path to common variant file e.g. qc_vcf_1000G.vcf.gz
  qcGroups:
  - UDP

tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools
```

Note, I get a similar error when running mae:
```
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmplef56382

Unlocking working directory.
WARNING: Using the mae defined genome instead of the globally defined one.
This will be deprecated in the future to allow for reference genomes to be defined in the sample annotation table. Please update your config and sample annotation table

UDP-1003_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1002_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1103_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1001_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

UDP-1101_RNA_snvParams.csv Param Files do not match. Updating to current Sample Annotation

check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpzk0vb3gx

Building DAG of jobs...
WorkflowError:
WorkflowError:
    MissingInputException: Missing input files for rule markdown:
    MAE/UDP--v32_results.md
    WorkflowError (rule mae_allelicCounts, line 111, /gpfs/scratch/drop/Scripts/MonoallelicExpression/pipeline/Snakefile):
        Function did not return str or list of str.
MissingInputException: Missing input files for rule markdown:
Scripts_MonoallelicExpression_pipeline_MAE_Datasets.md
```
