### ISSUE TITLE
Geuvadis dataset

### ISSUE THREAD

**Issue by gdeoli** [gagneurlab/drop#261]
Hi,

I was wondering whether you could share with me the detailed protocol that was used to process the 100 Geuvadis samples. I tried to reproduce your outcomes, but I'm facing this OUTRIDER error: "L-BFGS-B needs finite values of 'fn'". The AberrantSplicing mode ran successfully, though.

I have downloaded the fastqs of the same 100 samples you used and aligned them with STAR in twoPassMode. I have no clue what I might be doing wrong to not being able to reproduce your analysis. 

The detailed protocol from fastq, including STAR command line, references and any other caveats would be much appreciated as it would help me to shed some light on this matter.

Thanks

**Comment by vyepez88** [comment]
Hi Gustavo, thanks. If the aberrant splicing module ran successfully, then I guess the files were mapped correctly. Maybe it's a problem with the configuration? 
Our parameters in the config file are:
```
aberrantExpression:
  groups:
  - all
  minIds: 1
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: .05
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3
```
and in the sample annotation:
```
PAIRED_END     COUNT_MODE           COUNT_OVERLAPS     STRAND
TRUE           IntersectionStrict      TRUE            no
```
