### ISSUE TITLE
Aberrant genes found in AS but not AE

### ISSUE THREAD

**Issue by projectoriented** [gagneurlab/drop#264]
How do I interpret the situation where aberrant genes are found in AS but not AE for affected samples? Thanks in advance.

**Comment by nickhsmith** [comment]
I'm sorry for the delayed response. I can't say for sure (maybe @vyepez88 has another viewpoint), but just to clarify your situation you ran DROP in its entirety (DROP version 1.1.0?) and you have AS calls, but not AE calls.

Generally, the AS module I believe calls slightly more aberrant events than AE so it could be that nothing quite reaches the level of significance for AE, but does for AS. 

Could you also please answer some of the following questions. Thanks in advance
How many samples are you using in each group? 
What are your config-defined filters and cutoffs?

**Comment by vyepez88** [comment]
Hi, what exactly do you mean by affected samples? Usually, aberrant expression is caused by stop and frameshift variants. Also, by splice-disrupting variants that lead to a premature stop codon.
Aberrant splicing, on the other hand, can be caused by splice-region, but also missense and synonymous ones that activate a new splice site. These events won't necessarily cause aberrant expression, but aberrant splicing only.
Have a look at IGV and the `plotExpression` function from OUTRIDER of the individual cases.

**Comment by projectoriented** [comment]
Wonderful! Thank you for the responses.

By affected samples, I mean individuals with a clinical representation of a rare disease. I ran DROP version 1.1.0 with 125 samples belonging to 1 group: blood. The cutoffs are the default with the exception of `implementation` for AS

```
aberrantExpression:
  groups:
    - blood
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 0.05
  zScoreCutoff: 0
  maxTestedDimensionProportion: 3
aberrantSplicing:
  groups:
    - blood
  recount: false
  longRead: false
  keepNonStandardChrs: true
  filter: true
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA-BB-Decoder
  padjCutoff: 0.05
  zScoreCutoff: 0
  deltaPsiCutoff: 0.3
  maxTestedDimensionProportion: 6
```

Anyhow, I thought the same reasons as you both either 1) nothing reaches beyond the threshold for AE 2) caused by AS disrupting expression. We will explore IGV and `plotExpression` for now. Thank you so much for valuable input!
