### ISSUE TITLE
RNAseq_ASHG19 dataset - outrider does not repdroduce the outcomes

### ISSUE THREAD

**Issue by gdeoli** [gagneurlab/drop#297]
Hi,

In an attempt to validate drop outcomes, I've tried to reproduce the outcomes of NA11918 as described in **Case 1** (https://colab.research.google.com/drive/1YEic1daTeygmoPqZWaa5UOLgqopkfJFG#scrollTo=5AG0QkB_qVEd)

However, OUTRIDER does not set the gene MCOLN1 as aberrantly expressed. 

This is the configuration I'm using, with drop 1.1.1:

```
aberrantExpression:
  fpkmCutoff: 1
  groups:
  - drop
  implementation: autoencoder
  maxTestedDimensionProportion: 3
  padjCutoff: 0.05
  run: true
  zScoreCutoff: 0
```

COUNT_MODE = IntersectionStrict
COUNT_OVERLAPS = True

Is there anything I can do, to reproduce your outcomes?
