### ISSUE TITLE
'Calloc' could not allocate memory (18446744071562067968 of 1 bytes)

### ISSUE THREAD

**Issue by ym-chen** [gagneurlab/drop#370]
I have an error when I run the "rule aberrantSplicing" of AS module. I read other issues with similar situation to me. But I'm running on a cluster and can't provide hundreds of GB of memory for running. Please tell me what is the reason for this error? And how can I fix this? 
The error message is like : 
```
/home/my_conda_env/envs/drop/lib/python3.10/site-packages/drop/utils.py:89: Use
rWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.ext
ract.
  return  df[df[column].str.contains("(?:^|,)" + inner_regex + "(?:,|$)", na = False)]
Quitting from lines 87-88 (/tmp/973919.1.b2c_rd_s1.q/RtmpMcaIVo/file72874ee5502d/Overview.spin.Rmd)
Error in gsub(paste0("[\n]{2,}(", fence, "|    )"), "\n\n\\1", x) :
  'Calloc' could not allocate memory (18446744071562067968 of 1 bytes)
Calls: render ... call_block -> block_exec -> eng_r -> <Anonymous> -> gsub
In addition: Warning messages:
1: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
2: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
3: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
4: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
5: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
6: In checkReadType(x, type) :
  Read type was not specified!We will assume the default: 'j'
7: In instance$preRenderHook(instance) :
  It seems your data is too big for client-side DataTables. You may consider server-side processing: https://rstudio.github.io/DT/server.html
Execution halted
```
And the parameters of AS module in config.yaml are:
```
aberrantSplicing:
    run: true
    groups:
        - Batch
        - History
    recount: true
    longRead: false
    keepNonStandardChrs: false
    filter: false
    minExpressionInOneSample: 20
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 1
    zScoreCutoff: 0
    deltaPsiCutoff : 0.05
    maxTestedDimensionProportion: 6
```
