### ISSUE TITLE
Error in rule AberrantExpression_Overview_R

### ISSUE THREAD

**Issue by SunYinyi** [gagneurlab/drop#372]
Hi

We installed DROP and tried to run the demo data via drop demo, which worked fine. 
However, we are now trying to run DROP on our own data and seem to get some errors, confused for a long time. I hope you could give us some tips and tricks. Thanks!
we get the following errors (I pasted a part of log files).
```

[Fri Sep 23 16:07:46 2022]
rule AberrantExpression_Overview_R:
    input: /data2/syy/DROP/Scripts/html_functions.R, /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/ods.Rds, /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, Scripts/AberrantExpression/Overview.R
    output: /data2/syy/DROP/Output_test/html/Scripts_AberrantExpression_Overview.html
    log: /data2/syy/DROP/.drop/tmp/AE/Overview.Rds
    jobid: 73
    reason: Missing output files: /data2/syy/DROP/Output_test/html/Scripts_AberrantExpression_Overview.html; Input files updated by another job: /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/ods.Rds
    resources: tmpdir=/tmp

[Fri Sep 23 16:07:46 2022]
rule AberrantExpression_pipeline_OUTRIDER_Summary_R:
    input: /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/ods.Rds, /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, Scripts/AberrantExpression/pipeline/OUTRIDER/Summary.R
    output: /data2/syy/DROP/Output_test/html/AberrantExpression/Outrider/v29/Summary_outrider.html, /data2/syy/DROP/Output_test/html/AberrantExpression/Outrider/v29/OUTRIDER_results_outrider.tsv
    log: /data2/syy/DROP/.drop/tmp/AE/v29/outrider/OUTRIDER_summary.Rds
    jobid: 30
    reason: Missing output files: /data2/syy/DROP/Output_test/html/AberrantExpression/Outrider/v29/Summary_outrider.html; Input files updated by another job: /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/OUTRIDER_results.tsv, /data2/syy/DROP/Output_test/processed_results/aberrant_expression/v29/outrider/outrider/ods.Rds
    wildcards: annotation=v29, dataset=outrider
    resources: tmpdir=/tmp

[Fri Sep 23 16:07:52 2022]
Finished job 39.
60 of 78 steps (77%) done
Select jobs to execute...
[Fri Sep 23 16:07:59 2022]
Error in rule AberrantExpression_Overview_R:
    jobid: 73
    output: /data2/syy/DROP/Output_test/html/Scripts_AberrantExpression_Overview.html
    log: /data2/syy/DROP/.drop/tmp/AE/Overview.Rds (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 11 of /tmp/tmp03v06kak:
Command 'set -euo pipefail;  Rscript --vanilla /data2/syy/DROP/.snakemake/scripts/tmpqfjgqdmc.wBRender.R' returned non-zero exit status 1.
  File "/tmp/tmp03v06kak", line 11, in __rule_AberrantExpression_Overview_R
  File "/data2/syy/miniconda3/envs/drop_env_test/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[Fri Sep 23 16:08:29 2022]
Finished job 30.
61 of 78 steps (78%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-09-23T143438.125823.snakemake.log
```
**Error in screen**
```
Select jobs to execute...
Loading required package: SummarizedExperiment
Loading required package: MatrixGenerics
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians


Attaching package: 'MatrixGenerics'

The following objects are masked from 'package:matrixStats':

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, colCounts, colCu                                                                                                                                                             mmaxs, colCummins,
    colCumprods, colCumsums, colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colM                                                                                                                                                             adDiffs, colMads, colMaxs,
    colMeans2, colMedians, colMins, colOrderStats, colProds, colQuantiles, colRa                                                                                                                                                             nges, colRanks, colSdDiffs,
    colSds, colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, colWe                                                                                                                                                             ightedMeans,
    colWeightedMedians, colWeightedSds, colWeightedVars, rowAlls, rowAnyNAs, row                                                                                                                                                             Anys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, rowCumsums, row                                                                                                                                                             Diffs, rowIQRDiffs,
    rowIQRs, rowLogSumExps, rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians                                                                                                                                                             , rowMins, rowOrderStats,
    rowProds, rowQuantiles, rowRanges, rowRanks, rowSdDiffs, rowSds, rowSums2, r                                                                                                                                                             owTabulates, rowVarDiffs,
    rowVars, rowWeightedMads, rowWeightedMeans, rowWeightedMedians, rowWeightedS                                                                                                                                                             ds, rowWeightedVars

The following object is masked from 'package:Biobase':

    rowMedians

Loading required package: data.table

Attaching package: 'data.table'

The following object is masked from 'package:SummarizedExperiment':

    shift

The following object is masked from 'package:GenomicRanges':

    shift

The following object is masked from 'package:IRanges':

    shift

The following objects are masked from 'package:S4Vectors':

    first, second

  |                                                                                                                                                                                                                                            |.........................................                                                                                                                                                                                                                                  |  38%
  ordinary text without R code

  |                                                                                                                                                                                                                                            |................................................                                                                                                                                                                                                                           |  44%
label: unnamed-chunk-4 (with options)
List of 1
 $ echo: logi FALSE

  |                                                                                                                                                                                                                                            |.......................................................                                                                                                                                                                                                                    |  50%
  ordinary text without R code

  |                                                                                                                                                                                                                                            |..............................................................                                                                                                                                                                                                             |  56%
label: unnamed-chunk-5 (with options)
List of 1
 $ echo: logi TRUE

  |                                                                                                                                                                                                                                            |.....................................................................                                                                                                                                                                                                      |  62%
  ordinary text without R code

  |                                                                                                                                                                                                                                            |............................................................................                                                                                                                                                                                               |  69%
label: unnamed-chunk-6
Quitting from lines 102-105 (/tmp/RtmpiZ1Ldl/file61e6693359d8/Overview.spin.Rmd)                                                                                                                                                             
**Error: comparison (1) is possible only for atomic and list types**
In addition: Warning message:
In max(sampleID) : no non-missing arguments to max; returning -Inf

Execution halted
  |                                                                                                                                                                                                                                            |................                                                                                                                                                                                                                                                           |  14%
   inline R code fragments

  |                                                                                                                                                                                                                                            |.....................                                                                                                                                                                                                                                                      |  19%
label: unnamed-chunk-2
```


**Our config file**
 ```
projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: /data2/syy/DROP/Output_test/html
indexWithFolderName: true
root: /data2/syy/DROP/Output_test
sampleAnnotation: /data2/syy/DROP/Data_test/sample_annotation.tsv
geneAnnotation:
  v29: /data2/syy/DROP/Data_test/gencode.v29.gtf.gz
genomeAssembly: hg38
genome: /data2/syy/DROP/Data_test/ucsc.hg38.fasta
hpoFile: null
random_seed: true
exportCounts:
  geneAnnotations:
  - v29
  excludeGroups:
  - null
aberrantExpression:
  run: true
  groups: 
  - outrider
  fpkmCutoff: 1
  implementation: autoencoder
  padjCutoff: 1
  zScoreCutoff: 3
  maxTestedDimensionProportion: 3
  dassie:
    tssWindow: 500
    pasWindow: 1000
aberrantSplicing:
  run: flase
  groups: 
  - fraser
  recount: true
  longRead: false
  keepNonStandardChrs: false
  filter: false
  minExpressionInOneSample: 20
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 1
  zScoreCutoff: 3
  deltaPsiCutoff: 0.05
  maxTestedDimensionProportion: 6
mae:
  run: false
  groups:
  - mae
  gatkIgnoreHeaderCheck: true
  padjCutoff: 0.5
  allelicRatioCutoff: 0.7
  addAF: false
  maxAF: 0.001
  maxVarFreqCohort: 1
  qcVcf: /data2/syy/DROP/Data/qc_vcf_1000G.vcf.gz
  qcGroups:
  - mae
rnaVariantCalling:
  run: false
  groups:
  - batch_0
  - batch_1
  highQualityVCFs:
  - /data2/syy/DROP/Data/high_confidence_snps.vcf.gz
  - /data2/syy/DROP/Data/high_confidence_indels.vcf.gz
  dbSNP: /data2/syy/DROP/Data/dbSNP_chr21.vcf.gz
  repeat_mask: /data2/syy/DROP/Data/repeat_mask_chr21.bed
  createSingleVCF: true
  addAF: false
  maxAF: 0.001
  maxVarFreqCohort: 1
  hcArgs: null
  minAlt: 3
tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools
```
**Sample Annotation file**

```
RNA_ID	RNA_BAM_FILE	DNA_VCF_FILE	DNA_ID	DROP_GROUP	PAIRED_END	COUNT_MODE	COUNT_OVERLAPS	STRAND	HPO_TERMS	GENE_COUNTS_FILE	GENE_ANNOTATION	GENOME	SPLICE_COUNTS_DIR
017P6	/data2/syy/DROP/Data_test/rna_bam/017P6_sort.bam		017P6	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
017P7	/data2/syy/DROP/Data_test/rna_bam/017P7_sort.bam		017P7	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
P11DSN008-X	/data2/syy/DROP/Data_test/rna_bam/P11DSN008-X_sort.bam		P11DSN008-X	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
P11DSN008-T	/data2/syy/DROP/Data_test/rna_bam/P11DSN008-T_sort.bam		P11DSN008-T	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
19YQW100676	/data2/syy/DROP/Data_test/rna_bam/19YQW100676_sort.bam		19YQW100676	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
19YQW100675	/data2/syy/DROP/Data_test/rna_bam/19YQW100675_sort.bam		19YQW100675	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
ZHANGJUNXI	/data2/syy/DROP/Data_test/rna_bam/ZHANGJUNXI_sort.bam		ZHANGJUNXI	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
CAOYUERAN	/data2/syy/DROP/Data_test/rna_bam/CAOYUERAN_sort.bam		CAOYUERAN	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
XINGWEICHEN	/data2/syy/DROP/Data_test/rna_bam/XINGWEICHEN_sort.bam		XINGWEICHEN	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
JIANGYUXUAN	/data2/syy/DROP/Data_test/rna_bam/JIANGYUXUAN_sort.bam		JIANGYUXUAN	outrider,fraser	TRUE	IntersectionStrict	TRUE	no	HP:0000001			ucsc	
```
