### ISSUE TITLE
Estimated run-time for FRASER2

### ISSUE THREAD

**Issue by chrisodhams** [gagneurlab/drop#476]
Hi,

I was wondering how long a typical FRASER2 run is expected to be? 

If I peek at an ongoing job, it seems to hang or not update for at least a few days (5 days in this example), the tail is shown below:
```
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: rawCountsJnonsplit
Loading assay: jaccard
Loading assay: rawOtherCounts_jaccard
Loading assay: delta_jaccard
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Fri Jun  2 01:56:41 2023: jaccard
dPsi filter:FALSE: 45269        TRUE: 122243
Exclusion matrix: FALSE: 82522  TRUE: 84990
Fri Jun  2 01:57:52 2023: Injecting 266414 outliers ...
Fri Jun  2 07:01:04 2023: Run hyper optimization with 12 options.
```

I'm running 314 samples through FRASER2 using DROP v1.3.3 with the following config:

```
aberrantSplicing:
    run: true
    groups:
        - group1
    recount: false
    longRead: false
    keepNonStandardChrs: true
    filter: true
    minExpressionInOneSample: 20
    quantileMinExpression: 10
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    maxTestedDimensionProportion: 6
    genesToTest: null
    FRASER_version: "FRASER2"
    deltaPsiCutoff : 0.1
    quantileForFiltering: 0.75
```

My compute set-up is as follows (10 cores, 60GB each, run-time of 1 week):
```
#BSUB -q long
#BSUB -P bio
#BSUB -W 168:00
#BSUB -J drop
#BSUB -o logs/drop_%J.stdout
#BSUB -e logs/drop_%J.stderr
#BSUB -R "span[hosts=1] rusage[mem=60000]"
#BSUB -M 60000
#BSUB -n 10
```

Do you have any estimations with a similar number of samples? Do I trust that this is still running and wait longer? 

Many thanks,

Chris
