### ISSUE TITLE
Error in rule changeHeader

### ISSUE THREAD

**Issue by muhligs** [gagneurlab/drop#479]
Hi, 

I have succesfully made a run of AE, AS and MAE on a single sample with our own external counts. 
Everything went well. 

Now I wish to add the result of the RVC module. I have set AE, AS and MAE to false and RVC to true in the config file. 
I set the group in the config to mae, the group containing the one single sample:

```
rnaVariantCalling:
    run: true
    groups:
        - mae
    highQualityVCFs:
        - /faststorage/project/drop_rnaseq/referencefiles/mills_1000g/resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
        - /faststorage/project/drop_rnaseq/referencefiles/mills_1000g/resources_broad_hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf.gz
    dbSNP: /faststorage/project/drop_rnaseq/referencefiles/ncbi/hg38/00-All.vcf.gz
    repeat_mask: /faststorage/project/drop_rnaseq/referencefiles/repeatmask/hg38_repeatMasker_sorted.bed
    createSingleVCF: true
    addAF: true
    maxAF: 0.001
    maxVarFreqCohort: 0.05
    hcArgs: ""
    minAlt: 3
    yieldSize: 100000

```

I run with `snakemake --cluster "sbatch -N1 -n 3 --mem 250Gb --account momaguarantee --time=10:00:00" -j 50 -k --cores 3`

but I get errors in rule changeHeader,

`ln: failed to create hard link '/faststorage/project/drop_rnaseq/sandbox/full_reverse/Output/processed_data/rnaVariantCalling/out/bam/Q02A02716R/Q02A02716R_dropHeader.bam' => '/faststorage/project/drop_rnaseq/patients/Q02A02716R_N454-0052/filtered.bam': Operation not permitted`

The file filtered.bam (and bai) has full permission (777) and also the directory. 
Any help is appreciated. 

Best,
Morten
