### ISSUE TITLE
Missed call - not clear why

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#491]
Hi,
We did RNA-seq on a sample on which we know there is a very clear and strong splicing defect, as a positive control for the DROP pipeline.

The exon skipping is very obvious:
<img width="1038" alt="Screenshot 2023-08-28 at 9 37 43 PM" src="https://github.com/gagneurlab/drop/assets/47928628/86675bd9-6c2a-4ccc-bdaf-81b737da9a12">

However, DROP did not detect it.

Here are our config parameters:
```

aberrantSplicing:
    run: true
    groups:
        - GTEX100
    recount: false
    longRead: false
    keepNonStandardChrs: false
    filter: true
    minExpressionInOneSample: 20
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    maxTestedDimensionProportion: 6
    genesToTest: null
    FRASER_version: "FRASER2"
    deltaPsiCutoff : 0.1
    quantileForFiltering: 0.75
```

Here is the call in results_gene_all.tsv, but it was not in the final FRASER output:
```
seqnames	start	end	width	strand	sampleID	hgncSymbol	type	pValue	psiValue	deltaPsi	counts	totalCounts	meanCounts	meanTotalCounts	nonsplitCounts	nonsplitProportion	nonsplitProportion_99quantile	annotatedJunction	pValueGene	padjustGene
**	**	**	3650	+	Sample_RNA	**	jaccard	0.032264	0.31	-0.14	146	464	123.63	128.96	59	0.13	NA	both	0.90339	1
```

Can you help us understand why this did not get into the final call set and how we can fix this?

Also would appreciate to know if there is a fix, how we can do that without rerunning the whole pipeline, which takes a long time.

Thanks
