### ISSUE TITLE
Error in AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R

### ISSUE THREAD

**Issue by pkrithivasan** [gagneurlab/drop#526]
Hi,
Could you please help me troubleshoot the following error when running the aberrant splicing module?

```
[Fri Mar 22 18:38:56 2024]
rule AberrantSplicing_pipeline_FRASER_04_fit_hyperparameters_FraseR_R:
    input: /gpfs/commons/groups/clinical/pkrithivasan/CBI-342/GEN_n16_GTEx_n50_AS/Output/processed_data/aberrant_splicing/datasets/savedObjects/fraser/filter_FRASER2.done, Scripts
/AberrantSplicing/pipeline/FRASER/04_fit_hyperparameters_FraseR.R
    output: /gpfs/commons/groups/clinical/pkrithivasan/CBI-342/GEN_n16_GTEx_n50_AS/Output/processed_data/aberrant_splicing/datasets/savedObjects/fraser/hyper_FRASER2.done
    log: /gpfs/commons/groups/clinical/pkrithivasan/CBI-342/GEN_n16_GTEx_n50_AS/.drop/tmp/AS/fraser/04_hyper.Rds
    jobid: 0
    reason: Forced execution
    wildcards: dataset=fraser
    threads: 12
    resources: mem_mb=100000, mem_mib=95368, disk_mb=100000, disk_mib=95368, tmpdir=/gpfs/commons/groups/clinical/pkrithivasan/CBI-342/GEN_n16_GTEx_n50_AS/tmp

Rscript --vanilla /gpfs/commons/groups/clinical/pkrithivasan/CBI-342/GEN_n16_GTEx_n50_AS/.snakemake/scripts/tmpb865ksln.04_fit_hyperparameters_FraseR.R
Load packages
Loading assay: rawCountsJ
Loading assay: psi5
Loading assay: psi3
Loading assay: rawOtherCounts_psi5
Loading assay: rawOtherCounts_psi3
Loading assay: rawCountsJnonsplit
Loading assay: jaccard
Loading assay: rawOtherCounts_jaccard
Loading assay: delta_jaccard
Loading assay: delta_psi5
Loading assay: delta_psi3
Loading assay: rawCountsSS
Loading assay: theta
Loading assay: rawOtherCounts_theta
Loading assay: delta_theta
Fri Mar 22 18:39:25 2024: jaccard
dPsi filter:FALSE: 49215
Error in colVars(x, rows = rows, cols = cols, na.rm = na.rm, refine = refine,  : 
  Argument 'dim.' must be an integer vector of length two.
Calls: optimHyperParams ... colSds -> colSds -> .local -> <Anonymous> -> colVars
Execution halted

```
Config file parameters:
```
aberrantSplicing:
  run: true
  groups:
  - fraser
  recount: false
  longRead: false
  keepNonStandardChrs: false
  filter: true
  minExpressionInOneSample: 20
  quantileMinExpression: 10
  minDeltaPsi: 0.05
  implementation: PCA
  padjCutoff: 0.1
  maxTestedDimensionProportion: 6
  genesToTest: null
  FRASER_version: FRASER2
  deltaPsiCutoff : 0.1
  quantileForFiltering: 0.75

```
Thanks!
