### ISSUE TITLE
DESEq error on MonoallelicExpression_pipeline_MAE_deseq_mae_R module using demo dataset

### ISSUE THREAD

**Issue by Roshanshafiha** [gagneurlab/drop#601]
Hi, I am running the whole DROP pipeline (version-1.4.0) on the test data and I am getting the below error, may I know how can I fix this?

![Image](https://github.com/user-attachments/assets/fba67b9f-240c-458c-b6f8-e682eccf2d40)

**Below is my config file:**
```


projectTitle: Detection of RNA Outlier Pipeline
htmlOutputPath: Output/html
indexWithFolderName: true
root: Output
sampleAnnotation: Data/sample_annotation_relative.tsv
geneAnnotation:
  v29: Data/gencode_annotation_trunc.gtf
genomeAssembly: hg19
genome: 
  ncbi: Data/chr21_ncbi.fa
  ucsc: Data/chr21.fa
hpoFile: /projects/pipelines/drop_demo/hpo_genes.tsv.gz
random_seed: true
exportCounts:
  geneAnnotations:
  - v29
  excludeGroups:
    - mae
    - outrider_external
    - fraser_external

aberrantExpression:
    run: true
    groups:
      - outrider
      - outrider_external
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 1
    zScoreCutoff: 0
    genesToTest: "Data/genes_to_test.yaml"
    maxTestedDimensionProportion: 3
    yieldSize: 2000000

aberrantSplicing:
    run: true
    groups:
      - fraser
      - fraser_external
    recount: true
    longRead: false
    keepNonStandardChrs: false
    filter: false
    minExpressionInOneSample: 20
    quantileMinExpression: 10 
    quantileForFiltering: 0.95 
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 1 
    maxTestedDimensionProportion: 6
    genesToTest: "Data/genes_to_test.yaml"
    ### FRASER1 configuration for demo dataset
    FRASER_version: "FRASER" 
    deltaPsiCutoff : 0.05 

mae:
    run: true
    groups:
      - mae
    gatkIgnoreHeaderCheck: true
    padjCutoff: .5
    allelicRatioCutoff: 0.7
    addAF: false
    maxAF: .001
    maxVarFreqCohort: 1
    # VCF-BAM matching
    qcVcf: Data/qc_vcf_1000G.vcf.gz
    qcGroups:
      - mae
    dnaRnaMatchCutoff: 0.85

rnaVariantCalling:
    run: true
    groups:
      - batch_0
      - batch_1
    highQualityVCFs:
      - Data/high_confidence_snps.vcf.gz
      - Data/high_confidence_indels.vcf.gz
    dbSNP: Data/dbSNP_chr21.vcf.gz
    repeat_mask: Data/repeat_mask_chr21.bed
    createSingleVCF: true
    addAF: false
    maxAF: 0.001
    maxVarFreqCohort: 1
    hcArgs: null
    minAlt: 3
    yieldSize: 100000

tools:
  gatkCmd: gatk
  bcftoolsCmd: bcftools
  samtoolsCmd: samtools

```
I have downloaded the demo data from the following script download_data.sh :

```
#!/bin/bash
set -e

# get data
resource_url="https://github.com/gagneurlab/drop_demo_data/archive/refs/heads/main.zip"
tmpdir="$(dirname "$(mktemp)")"
wget -nc -P $tmpdir $resource_url

# if the directory Data does not exist
if [ ! -d "Data" ]; then
        unzip "$tmpdir/main.zip" 
        mv drop_demo_data-main/Data Data
        rm -rf drop_demo_data-main
else
    echo "Data directory not empty, is not updated"
fi

# unzip fasta
cd ./Data
if [ ! -f "chr21.fa" ]; then gunzip chr21.fa.gz; fi
```
