### ISSUE TITLE
ValueError in config.yaml file

### ISSUE THREAD

**Issue by helenine** [gagneurlab/drop#613]
Hello, I'm trying to run Aberrantsplicing module, here're my files:

[config.txt](https://github.com/user-attachments/files/20458716/config.txt)

[sample_annotation_new.txt](https://github.com/user-attachments/files/20458762/sample_annotation_new.txt)

I used "https://doi.org/10.5281/zenodo.6078396" this one as a External Group (just whole blood type) and the samples are non-stranded. However, our samples are reverse-stranded, so when I run the command it gives error.

```
 snakemake --cores 24 -p
ValueError in file /home/arda/rnaseq/DROP_project/config/Snakefile, line 12:
Data contains a mix of stranded and unstranded samples. Please analyze them separately.

  File "/home/arda/rnaseq/DROP_project/config/Snakefile", line 12, in <module>
  File "/home/arda/anaconda3/envs/drop_env/lib/python3.10/site-packages/drop/config/DropConfig.py", line 50, in __init__
  File "/home/arda/anaconda3/envs/drop_env/lib/python3.10/site-packages/drop/config/SampleAnnotation.py", line 27, in __init__
  File "/home/arda/anaconda3/envs/drop_env/lib/python3.10/site-packages/drop/config/SampleAnnotation.py", line 53, in parse

```

Since I used hg38 in our data, I did not use external counts with hg19. Which one is more appropriate and how can I overcome this problem?  Any help?

Kind regards,

Nur.

**Comment by vyepez88** [comment]
Hi Nur,
It's not really an error but a feature we introduced in one of our latest releases. We do not recommend merging stranded with unstranded data, especially for the splicing analysis. You also have to mind the correct genome build.

**Comment by helenine** [comment]
Thanks for reply,
I changed the info of the external counts as "reverse stranded" but now an another error occured:

```
No counts were generated.
Execution halted
[Sun Jun  8 02:45:19 2025]
Error in rule AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R:
    jobid: 20
    input: /home/arda/rnaseq/drop_family1_project/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/spliceSites_splitCounts.rds, Scripts/AberrantSplicing/pipeline/Counting/01_3_countRNA_nonSplitReads_samplewise.R
    output: /home/arda/rnaseq/drop_family1_project/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/sample_tmp/nonSplitCounts/sample_3619-A.done
    log: /home/arda/rnaseq/DROP_project/config/.drop/tmp/AS/fraser/nonsplitReads/3619-A.Rds (check log file(s) for error details)

RuleException:
CalledProcessError in file /mnt/disk1/arda_tmp/tmpwdz696qu, line 54:
Command 'set -euo pipefail;  Rscript --vanilla /home/arda/rnaseq/DROP_project/config/.snakemake/scripts/tmpnxsg05_n.01_3_countRNA_nonSplitReads_samplewise.R' returned non-zero exit status 1.
  File "/mnt/disk1/arda_tmp/tmpwdz696qu", line 54, in __rule_AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R
  File "/home/arda/anaconda3/envs/drop_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
No counts were generated.
Execution halted
[Sun Jun  8 02:51:10 2025]
Error in rule AberrantSplicing_pipeline_Counting_01_3_countRNA_nonSplitReads_samplewise_R:
    jobid: 19
    input: /home/arda/rnaseq/drop_family1_project/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/spliceSites_splitCounts.rds, Scripts/AberrantSplicing/pipeline/Counting/01_3_countRNA_nonSplitReads_samplewise.R
    output: /home/arda/rnaseq/drop_family1_project/processed_data/aberrant_splicing/datasets/cache/raw-local-fraser/sample_tmp/nonSplitCounts/sample_3618-B.done
    log: /home/arda/rnaseq/DROP_project/config/.drop/tmp/AS/fraser/nonsplitReads/3618-B.Rds (check log file(s) for error details)
```

I checked the bam files and nothing seems wrong.

**Comment by vyepez88** [comment]
Hi, you should only specify "reverse" if they were reverse, not if they were unstranded. Can you try running without the external samples? It is weird that the split read counting worked, but not the non-split read counting.

**Comment by AtaJadidAhari** [comment]
Hi @helenine , were you able to resolve this issue?

**Comment by helenine** [comment]
Unfortunately no, the demo had worked, but since I only have 6 bam files, I cannot test it without external counts.

**Comment by AtaJadidAhari** [comment]
I just noticed that right now you are using different gene annotation versions which might cause this issue (gencode29 and gencode47). You should use the same one for both your external and your own dataset, in this case gencode v.29. 

If you want to test without external counts, you can duplicate your samples and create 4 "fake" samples and rerun the pipeline to see if counting passes through.

Let us know how it goes!

**Comment by helenine** [comment]
Thank you for your helps. I edited config.yaml as;

```
projectTitle: "DROP Project Family1"
root: "/home/user/rnaseq/drop_family1_project"
htmlOutputPath: "/home/user/rnaseq/DROP_project"
sampleAnnotation: "/home/user/rnaseq/group1.tsv"
genome: "/home/arda/rnaseq/refseq/GRCh38.primary_assembly.genome.fa"
data:
  gtfFile: "/home/user/rnaseq/refseq/gencode.v47.primary_assembly.annotation.gtf"
  strand: "reverse"
  bamCounts: true
  output: "/home/user/rnaseq/drop_family1_project/output"

geneAnnotation:
  gencode47: "/home/user/rnaseq/refseq/gencode.v47.primary_assembly.annotation.gtf"

genomeAssembly: hg38

exportCounts:
  geneAnnotations:
    - gencode47

aberrantSplicing:
  run: true
  groups:
      - fraser
  filter: true
  minExpressionInOneSample: 20
  FRASER_version: "FRASER2"
  deltaPsiCutoff: 0.1
  quantileForFiltering: 0.75

monoAllelicExpression:
  run: false
```
and sample annotation file as:

[group1.txt](https://github.com/user-attachments/files/21055781/group1.txt)

However, now it gives errors and the log file is:

[2025-07-02T111225.402913.snakemake.log](https://github.com/user-attachments/files/21055846/2025-07-02T111225.402913.snakemake.log)
